<template>
  <div class="download">
    <div class="section-title">
      <h2>Download</h2>
    </div>
    <el-divider />
    <div class="content">
      <div class="contentmsg">
        <h2>Brief introduction of thoese files:</h2>
        <ul>
          <li>1. The source code contains the main code for SMI-BLAST running and the corresponding help files. The run.sh
            in source code is the main script file for running SMI-BLAST, and users need to configure corresponding file
            paths and associated models. The trained LTR model can directly configure the SMI-BLAST program to run, thus
            obtaining the results of different iterations of SMI-BLAST.</li>
          <li>2. Dependent software is the software environment that needs to be configured to run SMI-BLAST.</li>
          <li>3. The benchmark dataset and 84 feature datasets are the data set used in this study and the feature library
            generated by PSI-IN-ONE software, which is convenient for users to reproduce the experiment. If users need to
            experiment on other data sets, they need to reconfigure the benchmark data set and feature library.</li>
          <li>4. These ISH datasets are used to analyze the ISH errors of PSI-BLAST from the SCOPe 2.06 database. The
            specific error conditions can correspond to Figure 2 on the home page.</li>
          <li>5. The search results of SMI-BLAST are obtained based on different iteration times, users can directly use
            the results for further research</li>
        </ul>
      </div>
    </div>
    <div class="contentbox">
      <div class="box">
        <h3>Source code:</h3>
        <el-button type="success" plain round size="large">SMI-BLAST-V1</el-button>
        <h3>Trained learning to rank models of SMI-BLAST:</h3>
        <el-button type="success" plain round size="large">LTR model for fitst iteration</el-button>
        <el-button type="success" plain round size="large">LTR model for second iteration</el-button>
        <el-button type="success" plain round size="large">LTR model for fifth iteration</el-button>
        <el-button type="success" plain round size="large">LTR model for tenth iteration</el-button>
      </div>
      <div class="box">
        <h3>Dependency softwares:</h3>
        <el-button type="success" plain round size="large">Ubuntu 16</el-button>
        <el-button type="success" plain round size="large">Python 2.7</el-button>
        <el-button type="success" plain round size="large">PSI-BLAST 2.7.1</el-button>
        <el-button type="success" plain round size="large">HMMER-3.1b2</el-button>
        <el-button type="success" plain round size="large">Pse-in-One2.0</el-button>
        <el-button type="success" plain round size="large">RankLib-2.7</el-button>
      </div>
      <div class="box">
        <h3>Benchmark dataset:</h3>
        <el-button type="success" plain round size="large">SCOPe2.06</el-button>
        <h3>84 feature datasets of SCOPe2.06</h3>
        <el-button type="success" plain round size="large">Feature datasets</el-button>
      </div>
      <div class="box">
        <h3>ISH Datasets</h3>
        <el-button type="success" plain round size="large">True PSSM in PSI-BLAST</el-button>
        <el-button type="success" plain round size="large">False PSSM in PSI-BLAST</el-button>
        <el-button type="success" plain round size="large">ISH-MIX in PSI-BLAST</el-button>
        <el-button type="success" plain round size="large">ISH-NULL in PSI-BLAST</el-button>
        <el-button type="success" plain round size="large">ISH-ALL in PSI-blast</el-button>
      </div>
      <div class="box">
        <h3>Search results of SMI-BLAST:</h3>
        <el-button type="success" plain round size="large">Results at first iteration</el-button>
        <el-button type="success" plain round size="large">Results at second iteration</el-button>
        <el-button type="success" plain round size="large">Results at fifth iteration</el-button>
        <el-button type="success" plain round size="large">Results at tenth iteration</el-button>
      </div>
    </div>
  </div>
</template>

<script>

</script>

<style scoped>
.download {
  text-align: left;
}

.el-button {
  margin: 10px 0;
  width: 250px;
}

.content,
.contentbox {
  margin: auto;
  width: 1200px;
}

.contentbox {
  display: flex;
  flex-wrap: wrap;
}

.box {
  padding: 20px;
  width: 300px;
  height: 480px;
  text-align: center;
  margin: 10px auto;
  border-radius: 20px;
  background-color: #f1f1f1;
}

ul>li,
ol>li,
p {
  line-height: 1.8;
}
</style>